version: "3.9"
services:
  laravel-app:
    container_name: laravel-app
    build:
      args:
        user: www-data
        uid: 1000
      context: .
      dockerfile: ./Dockerfile
    # entrypoint: ./entrypoint.sh
    # command: ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"]
    volumes:
        - ./:/var/www/html
    working_dir: /var/www/html
    environment: 
        - APP_ENV=local
        - APP_KEY=base64:tLmYfUrrZITzLIkSjFnV+PCAFxkdU+duUxjVSIlrrHo=
        - APP_DEBUG=true
        - DB_CONNECTION=mysql
        - DB_HOST=database ## same as the database service name
        - DB_PORT=3306
        - DB_DATABASE=webservices
        - DB_USERNAME=db_user
        - DB_PASSWORD=db_user_pass
    restart: unless-stopped
    networks:
      mysql-phpmyadmin: {}
  laravel-nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-app
    networks:
      mysql-phpmyadmin: {}

networks:
  mysql-phpmyadmin:
    external: true